version: "3"

services:
  cr-user-service:
    build: cr-user-service
    image: cr-user-service:latest
    restart: always
    ports:
      - 8081:8081
      - 9091:9091
    networks:
      - my-network
  cr-conference-service:
    build: cr-conference-service
    image: cr-conference-service:latest
    restart: always
    ports:
      - 8082:8082
      - 9092:9092
    networks:
      - my-network
  cr-submit-service:
    build: cr-user-service
    image: cr-submit-service:latest
    restart: always
    ports:
      - 8083:8083
      - 9093:9093
    networks:
      - my-network
  cr-review-service:
    build: cr-review-service
    image: cr-review-service:latest
    restart: always
    ports:
      - 8084:8084
      - 9094:9094
    networks:
      - my-network
networks:
  my-network:
    # driver: overlay
    driver: bridge