server:
  port: 8083
spring:
  application:
    name: cr-submit-service
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      location: "tmp/tmp_file"

grpc:
  client:
    cr-conference-service:
      address: 'static://127.0.0.1:9092'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
