server:
  port: 8084
spring:
  application:
    name: cr-review-service

grpc:
  server:
    port: 9094
  client:
    cr-user-service:
      address: 'static://127.0.0.1:9091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext