server:
  port: 8082
spring:
  application:
    name: cr-conference-service

grpc:
  server:
    port: 9092
  client:
    cr-user-service:
      address: 'static://127.0.0.1:9091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext